project:
  type: website
  output-dir: docs
  resources:
    - cv.pdf

website:
  title: "HansK04"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: HAHA
      - href: pres.qmd
        text: Presentations
    right: 
      - text: CV
        href: cv.pdf

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto
